services:
  tracehawk:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./output:/output
      - ./.trivy-cache:/home/tracehawk/.cache/trivy

  frontend:
    build: ./frontend
    ports:
      - "5173:8080"
    depends_on:
      - tracehawk
