name: tracehawk

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./output:/output
      - trivy-cache:/home/tracehawk/.cache/trivy
      - ./test-repos:/app/test-repos

  frontend:
    build: ./frontend
    ports:
      - "5173:8080"
    depends_on:
      - backend

volumes:
  trivy-cache: